name: todo
description: Helper app to aid user with ETECSA services.

publish_to: "none"

version: 1.2.5+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.1
  intent: ^1.3.4
  permission_handler: ^3.1.0
  shared_preferences: ^0.5.7
  progress_dialog: ^1.2.4
  webview_flutter: ^0.3.22+1
  get_ip: ^0.4.0
  provider: ^4.1.3
  http: ^0.12.0+4
  dio: ^3.0.9
  device_proxy: ^0.0.3
  getflutter: ^1.0.11
  url_launcher: ^5.4.1
  font_awesome_flutter: ^8.5.0
  connectivity: ^0.4.8+6
  quick_actions: ^0.4.0+6
  apklis_api: ^0.0.1
  package_info: ^0.4.1
  flutter_html: any # it is any because there is a conflict with nauta_api
  flutter_downloader: ^1.4.4
  path_provider: ^1.6.11
  install_plugin: ^2.0.1
  # Internal dependencies
  contact_picker:
    path: ./contact_picker
  nauta_api:
    path: ./nauta_api

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  test:
  mockito:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - config/ussd_codes.json
    - logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "todo.png"
